export default {
  foods: [
    {
      id: 1,
      name: "Chevere Logs",
      cost: "£2.91",
      origin: "Nicaragua",
    },
    {
      id: 2,
      name: "Soup - Campbells, Chix Gumbo",
      cost: "£5.50",
      origin: "Mexico",
    },
    {
      id: 3,
      name: "Halibut - Steaks",
      cost: "£1.26",
      origin: "Colombia",
    },
    {
      id: 4,
      name: "Soup - Base Broth Beef",
      cost: "£9.97",
      origin: "Haiti",
    },
    {
      id: 5,
      name: "Tomatoes - Cherry, Yellow",
      cost: "£4.10",
      origin: "Japan",
    },
    {
      id: 6,
      name: "Pork - Ham Hocks - Smoked",
      cost: "£1.72",
      origin: "Macedonia",
    },
    {
      id: 7,
      name: "Cheese - Bocconcini",
      cost: "£3.16",
      origin: "China",
    },
    {
      id: 8,
      name: "Soup - Campbells Bean Medley",
      cost: "£6.98",
      origin: "France",
    },
    {
      id: 9,
      name: "Bar Nature Valley",
      cost: "£3.44",
      origin: "Panama",
    },
    {
      id: 10,
      name: "Beef - Ground Medium",
      cost: "£5.93",
      origin: "Brazil",
    },
    {
      id: 11,
      name: "Five Alive Citrus",
      cost: "£9.46",
      origin: "China",
    },
    {
      id: 12,
      name: "Carbonated Water - Peach",
      cost: "£6.65",
      origin: "Ireland",
    },
    {
      id: 13,
      name: "Dried Peach",
      cost: "£2.54",
      origin: "Indonesia",
    },
    {
      id: 14,
      name: "Wine - Pinot Grigio Collavini",
      cost: "£8.36",
      origin: "Canada",
    },
    {
      id: 15,
      name: "Garlic - Peeled",
      cost: "£4.29",
      origin: "Indonesia",
    },
    { id: 16, name: "Mortadella", cost: "£9.97", origin: "Mexico" },
    {
      id: 17,
      name: "Muffin - Banana Nut Individual",
      cost: "£3.45",
      origin: "Madagascar",
    },
    {
      id: 18,
      name: "Hipnotiq Liquor",
      cost: "£1.06",
      origin: "China",
    },
    {
      id: 19,
      name: "Onions - Spanish",
      cost: "£9.38",
      origin: "Brazil",
    },
    {
      id: 20,
      name: "Potatoes - Fingerling 4 Oz",
      cost: "£7.88",
      origin: "Vietnam",
    },
    {
      id: 21,
      name: "Pineapple - Golden",
      cost: "£8.62",
      origin: "Mexico",
    },
    {
      id: 22,
      name: "Lettuce - Arugula",
      cost: "£7.72",
      origin: "China",
    },
    {
      id: 23,
      name: "Wine - Pinot Noir Mondavi Coastal",
      cost: "£8.51",
      origin: "Sweden",
    },
    {
      id: 24,
      name: "Soup - French Onion, Dry",
      cost: "£6.95",
      origin: "China",
    },
    {
      id: 25,
      name: "Chicken - Livers",
      cost: "£1.49",
      origin: "Armenia",
    },
  ],
};
